### ISSUE TITLE
blokus_corners_heuristic fails on start_state

### ISSUE THREAD

**Issue by alonitac** [alonitac/BlokusAI#1]
** in branch bfs_dfs_first_goal_search **
I've changed A* to put heuristic(start_state, problem) as the cost of the first Node, as you suggested. But now blokus_corners_heuristic fails, perhaps you can quickly resolve it? If not I'll try...

Steps to reproduce:
1. run `python3 game.py -p tiny_se corners -H blokus_corners_heuristic `

**Comment by alonitac** [comment]
same for blokus_cover_heuristic

**Comment by franwe** [comment]
This can be solved with a small change in the **a_star_search** function. 

`fringe.push(Node(start_state, None, None, 0), heuristic(start_state, problem))`
We cannot compute a heuristic-value for the start_state. The heuristic check how far the covered spots are from the targets, but the start_state is an empty board where nothing is covered yet, so the heuristic does not know to where the targets should be distant to. 

So instead of giving this entry in the priority queue the calculated heuristic-value we can just give it priority 1. 
`fringe.push(Node(start_state, None, None, 0), 1)`
At this state the queue has only one element, so the priority value does not matter. Am I right?
